# Generated by Django 6.0.3 on 2026-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='RENAVAM')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('type', models.CharField(choices=[('guincho', 'Guincho'), ('caminhao', 'Caminhão'), ('utilitario', 'Utilitário'), ('outro', 'Outro')], default='guincho', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
